### ISSUE TITLE
GeofenceReceiver is never triggered.

### ISSUE THREAD

**Issue by maurizi** [maurizi/Geoclock#16]
`locationClient.addGeofences` calls it's callback with a successful status, but the broadcast receiver is never called, even if I enable mock locations and move in and out of the geofence area.

**Comment by ivanarellano** [comment]
The GeofenceReceiver is being killed once returning from onReceive().

> If this BroadcastReceiver was launched through a <receiver> tag, then the object is no longer alive after returning from this function.
> [http://developer.android.com/reference/android/content/BroadcastReceiver.html#onReceive%28android.content.Context,%20android.content.Intent%29]

**Comment by ivanarellano** [comment]
@maurizi This is fixed in the current master build now.
