### ISSUE TITLE
Investigate BroadcastReceiver export

### ISSUE THREAD

**Issue by ivanarellano** [maurizi/Geoclock#22]
Test whether the receiver can receive system level broadcasts. [This stackoverflow page](http://stackoverflow.com/questions/27458207/what-is-the-use-of-androidexported-true-in-broadcastreceiver) makes me suspect that the "false" export makes this not work.

Edit: Test with a boot completed intent on the receiver.

**Comment by maurizi** [comment]
Tested both and they both work :)
